AWSTemplateFormatVersion: '2010-09-09'
Description: CF Template for Auto Scaling Group and Application Load Balancer
Parameters:
  HWImageID:
    Description: Please enter Image ID 
    Type: String
    Default: "ami-0a3c3a20c09d6f377"
  HWSubnetID:
    Description: Please enter Subnet ID 
    Type: String
    Default: "subnet-06c39d3dbf73e9d78"
  HWSecurityGroupIds: 
    Description: Please enter Security Group ID 
    Type: String
    Default: "sg-0df56033e7d899536"
  Purpose:
    Description: This is the Tag for the Purpose of the task
    Type: String
    Default: "Homework"

Resources:
  HoweworkLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: HWLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref HWImageID
        InstanceType: t2.micro
        KeyName: cigdem@hp
        SecurityGroupIds: 
         - !Ref HWSecurityGroupIds
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash 
            sudo yum update -y 
            sudo yum install httpd -y 
            echo "home work complete" >> /var/www/html/index.html
            sudo systemctl start httpd 
            sudo systemctl enable httpd

  HWAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
      DesiredCapacity: "3"
      LaunchTemplate: 
        LaunchTemplateId: !Ref HoweworkLaunchTemplate
      LoadBalancerNames: 
        - String
      MaxSize: "5"
      MinSize: "2"
      Tags: 
        - Key: "Purpose"
          Value: !Ref Purpose
        - Key: "Name"
          Value: "hw-asg-cf"