AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyHomeworkVPC: # Logical Name or Logical ID, must be unique within the template
    Type: AWS::EC2::VPC
    Properties: 
        CidrBlock: 10.0.0.0/23
        Tags: 
          - Key: "Purpose"
            Value: "Homework"